### ISSUE TITLE
Does this just support features?

### ISSUE THREAD

**Issue by judgej** [geo-io/wkt-parser#2]
Does this package just parse features in WKT form? So points, lines, shapes etc. are supported, but it won't parse a projection, coordinate reference system, ellipsoids, datums etc. Is that the correct scope?

Thanks.

**Comment by jsor** [comment]
Yes, that is correct. The [crs](https://github.com/geo-io/crs) package might be able to handle CRS WKT definitions in the future, but i have no plans to implement this at the moment.

**Comment by judgej** [comment]
Okay, thanks.
